title: Ben Moll
description: Portfolio | Meteorology | Data Science

remote_theme: "mmistakes/minimal-mistakes@4.27.3"

plugins:
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
